<?xml version="1.0"?>
<robot name="4wd_robot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="wheelbase" value="0.3"/>
  <xacro:property name="track" value="0.25"/>
  <xacro:property name="body_length" value="0.4"/>
  <xacro:property name="body_width" value="0.3"/>
  <xacro:property name="body_height" value="0.08"/>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <origin xyz="0 0 0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>

  <xacro:macro name="wheel" params="name x y">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.2"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} -${body_height/2 + wheel_radius}" rpy="0 1.5708 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel name="front_left_wheel"  x="${wheelbase/2}"  y="${track/2}"/>
  <xacro:wheel name="front_right_wheel" x="${wheelbase/2}"  y="-${track/2}"/>
  <xacro:wheel name="rear_left_wheel"   x="-${wheelbase/2}" y="${track/2}"/>
  <xacro:wheel name="rear_right_wheel"  x="-${wheelbase/2}" y="-${track/2}"/>

  <gazebo>
    <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace>/</namespace>
      </ros>
      <left_wheel>front_left_wheel_joint</left_wheel>
      <left_wheel>rear_left_wheel_joint</left_wheel>
      <right_wheel>front_right_wheel_joint</right_wheel>
      <right_wheel>rear_right_wheel_joint</right_wheel>
      <wheel_separation>${track}</wheel_separation>
      <wheel_diameter>${2*wheel_radius}</wheel_diameter>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>
      <command_topic>cmd_vel</command_topic>
      <odometry_topic>odom</odometry_topic>
    </plugin>
  </gazebo>
</robot> 